---
title: "assignment01_questions"
author: "Jeff Nguyen"
date: "18/09/2020"
output: html_document
---


UNIVERSITY OF SOUTHERN CALIFORNIA
Marshall School of Business
FBE 506 Quantitative Methods in Finance
M. Safarzadeh

Assignment # 1					Student Name: ____________________

1. Solve the following equations:
a. x2 + 2x - 8 = 0. 
b. x2 – 9 = 0
c. x3 - x2 + 4x - 4 = 0.
d. x5 + 3x2 – 8 = 0.

2. Future Value Problem: Find the compounded value of 100 deposited at a rate of 6% for 5 years, if the interest is compounded annually, quarterly, monthly, daily and continuously.

Note: For a discrete compounding, the formula is S = A(1 + r/n )nt, where S is the compounded value, A is the initial investment, r is the interest rate, n is the number of time the interest is compounded a year, and t is the number of years. If the interest is compounded continuously, the compounding formula is S = Aert. 

3. Present Value Problem: An investment is expected to have a return of 22000 at the end of the first year, 28500 at the end of the second year, 32000, at the end of the third year, 18000 at the end of the fourth year, and 12000 at the end of the fifth year. At the end of the fifth year the business is expected to have a market value of 52000. What is the present value of the future returns if the interest rate is 6%? What is the present value of the investment?
 
Note: The present value of the expected future returns for the next n years is PV = R1/(1+ r)1+ R2/(1+r)2+ R3/(1+r)3 + ...... +Rn/(1+r)n, where PV is the present value, Ri is the return in the ith year, r is the rate of return or interest rate, and n is the number of years. 

4. Net Present Value Problem: Net present value, NPV is the difference between the value of the initial investment, Io and the present value of investment, PVI. If NPV > 0, the investment is profitable. If NPV < 0, the investment will have a loss. Suppose an investment is expected to have returns of 22000, 28500, 32000, 18000, and 12000 at the end of each year for the next five years. At the end of the fifth year, the business is expected to have a market value of MV = 52000. Given that the initial investment is 120000, what is the net present value of the investment if the discount rate is 6%?

5. Perpetuity: A Perpetuity is a security that yields a stream of annual payments at an annual rate of r forever. The value of the perpetuities is decided by the sum of the present value of the stream of payments for infinite number of years. That is, PV = sum(R/(1+r)t) when t =∞. Here, R is the annual payments and r is the discount factor. Suppose a perpetuity yields an annual payments of 1 forever. What is the present value of the perpetuity if discount rate is 5%?

6. Internal Rate of Return: Internal rate of return is the interest rate at which NPV = 0 or PVI = Io. 
a. For the present value problem in question 4 find the internal rate of return.
b. Find the rate of return on a 24,000 investment with an annual return of 4,500 for five years and a scrap value of 2,500 at the end of the fifth year.



