---
title: "assignment03_questions"
author: "Jeff Nguyen"
date: "18/09/2020"
output: html_document
---
UNIVERSITY OF SOUTHERN CALIFORNIA
Marshall School of Business
FBE 506 Quantitative Methods in Finance
M. Safarzadeh


Assignment # 3

All the calculations for this assignment should be done manually.  The graphs on question 5 should be done using R.

1. Find the extreme points of the following functions and test for maximum, minimum, or      inflection points.

  a) y = x2 - 6x + 5		
  b) y = -x2 + 6x - 5
  c) y = 2x3 - 15x2 + 36x + 10    
  d) y = x3 - 3x2 + 3x
  e) y = (x - 1)3                          
  f) y = (x2 - 1)2
  g) y = ln[(x + 1)/(x2 + 3)] 

2. Find the linear approximations of the functions (a) and (d) of question 1 at xo = 1. Find the linear and the quadratic approximations of the functions (d) and (e) at xo = 1.    
   	
3. The short-run production technology of a firm is given as: Q = 100N - N2. The firm has no constraint on on labor input. How many labor is needed to maximize the output? 

4. Find price elasticity of demand for the following demand functions. (Hint: Price elasticity of demand, εp, is defined as εp=dq/dp  p/q). 
a) q=100-1.6P, when price is P = 45.00
b) q=100/P^3 , when price is P = 20.00
c) q = 10P-1.8Y.6, when price is P = 20.30 and income Y = 5800.00.

5. For the total cost function, TC=10+26q-3.5q2+1/3 q^3, 
a.  Graph the function.
b.  Find average total cost function (ATC) and graph it.
c.  Find average variable cost function (AVC) and graph it.
d.  Find Marginal cost function (MC) and graph it.
e.  Graph ATC, AVC, and MC in one coordinate system and comment about their relations.




